### PR TITLE
Move php out of community.css

### PR DESCRIPTION
**Pull request by paxcodes**
I can't generate the hashes properly. When I run `generate-hashes` it updates the hash of everything instead of only community.css-related changes.

```sh
➜  xxhsum -V
xxhsum 0.7.3 (64-bit x86_64 + SSE2 little endian), Apple Clang 11.0.0 (clang-1100.0.33.17), by Yann Collet
```

### CODE REVIEW

**Comment by jackdouglas** [comment]
generate-hashes will err on the side of caution when it runs — it usually doesn't matter if it regenerates a hash for a file that hasn't changed.

**Comment by paxcodes** [comment]
I looked more closely and it seems like that hashes are not regenerated but rather the files' order was moved around. 

topanswers__Git_ _You can see that `clike` and `clojure` still has the same hash_

**Comment by jackdouglas** [comment]
that's interesting — if I rerun generate-hashes multiple times I don't get a different sort order each time, do you?

if you pipe each of the `find` commands to `sort` do you still get an unstable order?

eg

```
exec("find -L get/lib -maxdepth 19 -type f \( -name '*.js' -o -name '*.css' \)",$files);
```
->
```
exec("find -L get/lib -maxdepth 19 -type f \( -name '*.js' -o -name '*.css' \) | sort",$files);
```

**Comment by paxcodes** [comment]
The order is consistent on every run. It's simply ordered differently compared to yours which seems to be the experience of [others](https://serverfault.com/questions/181787/find-command-default-sorting-order#comment158681_181787)?

Bottom line though, 

> If you want a consistent order, feed the output through an extra sorting stage. [[source](https://serverfault.com/a/181815/178732)]

I'll send a PR to sort the files so it's ordered consistently regardless of the system.

**Comment by jackdouglas** [comment]
I thought about merging your PR before my conflicting commit, but when I looked into it further I realised that it made more sense this way round — sorry for the extra work, but please can you revise your change?

The good news is you won't actually need community_auth.css any more, which I'm glad about :)

**Comment by paxcodes** [comment]
Ready @jackdouglas

**Comment by jackdouglas** [comment]
I hope I didn't mess that up

**Pull request merged**
