### PR TITLE
Remove php in question.js

### PR DESCRIPTION
**Pull request by paxcodes**
Would `QUESTION_HAS_FIDDLE` be an appropriate name for the js variable that is meant to replace `isset($_GET['fiddle'])`?

### CODE REVIEW

**Comment by paxcodes** [comment]
I used jQuery here because of comment in [chat](https://topanswers.xyz/transcript?room=756&id=54508#c54508) and it looks like if the code is within define(), jquery is already available then.

But I also read this recently, 
> We have started to move away from using jQuery in the front-end code in favour of native (modern) Javascript. —[meta.ta](https://topanswers.xyz/meta?q=1183)

Is it correct then that I don't use jQuery from here on?

**Comment by jackdouglas** [comment]
> Is it correct then that I don't use jQuery from here on?

No not at all — please carry on using it where it is already in use. We may never get rid of it, but I'm removing it from certain areas as an experiment to see what is possible, eg the new 'tags' page!

**Comment by paxcodes** [comment]
Hey @jackdouglas, when do you think you'd have time to merge this so that I'd make sure I'll rebase it right before then?

**Comment by jackdouglas** [comment]
I realised I missed your first question in this thread

> Would QUESTION_HAS_FIDDLE be an appropriate name for the js variable that is meant to replace isset($_GET['fiddle'])?

QUESTION_IS_FROM_FIDDLE would be closer to that meaning — there is a link on db<>fiddle that says "ask a question about this fiddle" and it means it is from that link.

`questionIsNew` should be something like `QUESTION_IS_NEW` to be consistent, shouldn't it?

> when do you think you'd have time to merge this so that I'd make sure I'll rebase it right before then?

I'm free today if you have the time for the tweaks and then a final rebase?

**Comment by paxcodes** [comment]
Sorry I'm not available for the rest of the day. If I rebase tonight, will
that work?

**Comment by paxcodes** [comment]
I just realized "tonight" means differently for you since that'd be right now in the UK 😅

I mean to say, I'll rebase it "tonight" my time and it will be ready for you in the morning tomorrow (your time)?

**Comment by jackdouglas** [comment]
that's fine :)

I guess we should try and figure out how to manage merges so you don't have to do needless rebasing — I wonder if we should just exclude the generated files (get/require.config.js and hash.php) from your PRs, what do you think? It's otherwise a bit inconvenient for you to have to schedule things around me, isn't it

**Pull request merged**
